### PR TITLE
Fix #13 Suggest parameter name in "extract value" refactoring.

### LINKED ISSUE #13: Suggest parameter name in "extract value" refactoring
In the following expression:

```
print("foo");
```

When I call the extract value refactoring on `"foo"`, it would be cool if the suggested names contained:

- `val` (the parameter name, taken from the signature of `print`)
- possibly the string content (`foo`), if it matches `\w+`

Those would be more meaningful than `string` :)

### PR DESCRIPTION
**Pull request by NiematojakTomasz**
Unfortunately I wasn't able to test it in action (IDE). I wasn't able to install it. But you can postpone merging this feature until I will be able to fully test it. For now I would be glad to hear if you have any comments - to the naming rules or to the code. Thanks!

String literal name proposals:
Name proposal from string value is constructed only if string value is not empty and contains only letters.
Name proposal is lowercase version of string literal value.

Invocation argument value name proposals:
For all cases with few exception proposed name is exact value of parameter name.
For variadic parameters if more than one value is provided to it number of parameter is appended to it.
For anonymous arguments always number of parameter is appended to it.
Proposals for indirect invocations are not supported.
Proposals for arguments in not-first arguments lists of functions are not supported.

String literal name proposals border cases (Tested):
- empty string
- string literal containing other letters than characters (Shouldn't work, shouldn't provide proposal, shouldn't throw exception)
- string literal containing only characters other than letters (Shouldn't work, shouldn't provide proposal, shouldn't throw exception)
- string literal containing only letters

Invocation argument value name proposals border cases (Tested):
- named argument
- positional argument
- sequenced argument
- arguments on function which has more than one parameters list (Shouldn't work, but also shouldn't cause internal error)
- variadic parameter
  - single argument for variadic parameter
  - multiple arguments for variadic parameter
- argument to function with no parameters (Shouldn't compile, but also shouldn't cause internal error)
- generic function with variadic parameter
- class with variadic parameter
- indirect invocation (Shouldn't work, but also shouldn't cause internal error)
- Java method invocation (Shouldn't work, but also shouldn't cause internal error)
- Parameter named with keyword
- Parameter name starting with uppercase letter

### CODE REVIEW

**Comment by bjansen** [comment]
FTR, if you want to test your changes in Eclipse, you need to follow these steps every time you make a modification in ceylon-ide-common:

* call `ant publish ide-quick` in ceylon-ide-common
* refresh the proxy project `com.redhat.ceylon.ide.common-1.2.1.car`

`com.redhat.ceylon.ide.common-1.2.1.car` is a subproject that can be found in `.../ceylon-ide-eclipse/required-bundle-proxies/com.redhat.ceylon.ide.common-1.2.1.car`, it allows overriding the version of ceylon-ide-common that's shipped in Ceylon IDE with the CAR you just built.

This is explained in the [readme](https://github.com/ceylon/ceylon-ide-eclipse/#developing-the-plugin-inside-eclipse).

**Comment by bjansen** [comment]
Additional note: it looks like your function is not generating escaped identifiers, meaning it will output invalid identifiers such as `void` or `Argument` like in your unit tests. It would be nice if you could fix that and use `escaping.escape()`.

**Comment by NiematojakTomasz** [comment]
@bjansen fixed and tested manually in eclipse. Works as expected : )
I hope you don't mind I added new escaping method. I assumed that if for some reason someone started name argument with uppercase it should be preserved in variable name proposal. Even if I cannot come up with example which doesn't give you a bad taste in mouth.
If we would someday want to support named arguments in java methods, than it's a different case, because name comes from place with potentially different naming conventions.

Thanks for hints!

**Comment by bjansen** [comment]
It's nice to see documented *and* tested code ;) Thanks!

**Pull request merged**
